updated and hopefully fixed render_readme.yml
epiverse-trace/epiparameter pull request #34
Opened 2022-10-05 14:52 UTC by joshwlambert

I had based the render_readme.yml from `readepi`. However, there have been some updates to the same workflow on `linelist`. The render_readme.yml now matches the `linelist` yaml with the exception of the packages installed.

2022-10-05 15:12 UTC, Bisaloo requested changes
Now that I'm looking at it, I believe the workflow from linelist should be updated as well :grimacing:. Sorry about this.

2022-10-05 15:42 UTC, joshwlambert commented on .github/workflows/render_readme.yml
> +        uses: r-lib/actions/setup-pandoc@v1
Updated to v2 in [d7c90c5](https://github.com/epiverse-trace/epiparameter/commit/d7c90c5e62697b8211acea0a1e414e6628f49b2e)

2022-10-05 15:42 UTC, joshwlambert commented on .github/workflows/render_readme.yml
> +        uses: r-lib/actions/setup-r@v1
Updated to v2 in [d7c90c5](https://github.com/epiverse-trace/epiparameter/commit/d7c90c5e62697b8211acea0a1e414e6628f49b2e)

2022-10-06 08:01 UTC, Bisaloo approved these changes
I just manually triggered a README render and it looks fine. It think we can merge this PR even though R CMD check didn't run.
What do you think?

2022-10-06 09:03 UTC, merged